blank_issues_enabled: false
contact_links:
  - name: Contact Us
    url: https://github.com/Kali99xx/Geeked
    about: Submit feedback and contact the Geeked support team for things like Billing, Enterprise, and other issues.
  - name: Geeked GitHub Issue Search
    url: https://github.com/Kali99xx/Geeked/issues?q=is%3Aissue+is%3Aopen+a+sort%3Areactions-%2B1-desc
    about: Search Geeked's open issues and feature requests.
  - name: Geeked Documentation
    url: https://github.com/Kali99xx/Geeked
    about: Documentation for known issues, troubleshooting, keyboard shortcuts, features, telemetry table, and more!
  - name: Geeked Discord Community
    url: https://discord.com/invite/geeked
    about: Discuss what you want to see in a Modern ADE with a community of other Geeked users.
  - name: Geeked Preview Slack Community
    url: https://github.com/Kali99xx/Geeked
    about: Discuss give feedback on the new features with other Geeked Preview users.
  - name: Geeked Changelog
    url: https://github.com/Kali99xx/Geeked
    about: See our changelog to learn about new features, improvements, and bug fixes.
  - name: Geeked Homepage
    url: https://github.com/Kali99xx/Geeked
    about: Homepage for all things Geeked.
  - name: Geeked Licenses
    url: https://github.com/Kali99xx/Geeked
    about: See the open source projects Geeked depends on and their licenses.
